# Generated by Django 5.1.6 on 2025-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_detail_patient_address_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Detail',
        ),
        migrations.AlterField(
            model_name='patient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nextvisit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
