# Generated by Django 5.1.6 on 2025-02-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_detail_alter_patient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nextvisit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
