# Generated by Django 5.1.6 on 2025-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_mobile_alter_patient_nextvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nextvisit',
        ),
    ]
