# Generated by Django 5.1.6 on 2025-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
